---
title: "Yunfei_index"
---

I am consistently being asked by my friends if there is any wine that I recommend them to buy. However, there are so many features to consider when answering such questions, for example, dry v.s. sweet, price, white or red, etc. Inspired by those questions, I am thinking about making a series of visualization to help my friends choose the next bottle to buy. They would gain a basic understanding of wine types by looking at the visualizations, and hopefully can decide which would be on their wine tasting list.



## Plot 1 The International Wine Industry
### Explanation
This viz would show the distribution of wineries in the world. There are around 4,000 producers in the dataset, and mainly located in Eastern Europe, the U.S., Southern parts of South America and Africa, and Australia. France and Italy are no doubt the counties possess the most wineries, with 1,907 and 958 producers respectively. The countries close to them, including Spain and Germany also have relatively large share of the wine producing market. In the Southern Hemisphere, Chile, Argentina, South Africa, and Australia have some good wineries as well. Those countries are actually in the similar latitudes, which makes sense as grapes require a proper temperature range to grow.

### Design Considerations
The first plot is aimed to provide an overview of the global wine industry, so it is at country level. The filling color of the countries shows the number of producers, and in the tooltip, aside from country names and number of producers, number of products also showed to provide with more information. The color scale used is white to purple, reflecting the color of wine, the darker the more wineries there are in the country.

## Plot 2 Wine Types and Varieties
### Explanation
The second plot is expected to be informative for people who are not familiar with grape varieties. Wines are categorized into red, white, rose, and sparkling, and this level of categorization is straightforward. There are hard and fortified wines as well, featuring with very high abv (~40), which do not enjoy a large group of consumers compared to the 4 types of wines mentioned above.

This plot contains a dropdown button, which can be used to select a type of wine. The plot shows the abv and degree of the wines and what main grape variety they are made by. “Variety” is the second level of the wine category if people are looking for products. For example, if you are entering Trader Joe’s, you may see signs of “Cabernet Sauvignon”, “Chardonnay”, and “Merlot” on the shelf of wines. Those are the (main) grape variety of the wine.

Abv, or alcohol by volume, is the measurement of how much alcohol it contains in each unit. In practice, some wines have an abv range instead of the exact value, such as “11% - 13%”. In this case, the value is averaged to 12%. Degree, or the serving temperature, can be vary among types and grape varieties as well. For example, sparkling is better to be served iced cold.

We can start by looking at the red wine type, which I believe has the most products. In this type, wines made by different grape varieties have a similar degree and abv. Cabernet Sauvignon has a small variation in abv, while Grenache has a larger variation, from 9 to 17.

If we start to explore other types of wines, Moscato can be used for both white and sparkling, and the abv of this variety is low, from 2 to 7, which would be favored by people who cannot handle a lot of alcohol (like my roommate).

### Design Considerations
Each data point stands for a product, color-coded by grape varieties so that the audience can have an overall understanding of the abv and serving temperature of types of wines. I applied a dropdown button for wine type so that there will not be a lot of varieties in one plot, and also wine type is the most intuitive way to categorize wines that do not require any background knowledge in wines. Opacity is applied as some data points might have overlap.

## Plot 3 Detailed Information
### Explanation
After gaining a basic understanding of different varieties, audience would expect some more detailed information. This innovation view links the three vizs together. When looking at the top-left viz (abv & degree), audiences can brush an area of product, and the following vizs would highlight other information including sweet, acidity, body, and tannin.

For example, if an audience likes sweet and does not like sour, he/she can start with the top right plot (sweet & sour), and select the bottom-right part (sweetness is high while acidity is low). After that, Moscato and Chardonnay would be highlighted and there is a slight difference in body for those two grape varieties, which the audience can choose accordingly.

Design Considerations
Brushing is the main design in this plot. As there are many features in wines, and different people may focus on different factors. It is hard to plot them into a high-dimensional space, and hard to read, so brushing make it possible to look at multiple features at once.

## Plot 4 Product Information
(this part is in progress, aiming to show the product price and review information to help audiences make purchase decisions)